linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - godot

linters-settings:
  goimports:
    local-prefixes: github.com/cleeryy/clarr

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
