version: 2

builds:
  - id: clarr
    main: ./cmd/clarr/main.go
    binary: clarr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: clarr
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

dockers:
  - id: clarr-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/cleeryy/clarr:{{ .Version }}
      - ghcr.io/cleeryy/clarr:latest
    dockerfile: Dockerfile.goreleaser

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
