version: 2

builds:
  - id: clarr
    main: ./cmd/clarr/main.go
    binary: clarr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: clarr
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - id: clarr-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/cleeryy/clarr:{{ .Version }}-amd64
      - ghcr.io/cleeryy/clarr:latest-amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/amd64

  - id: clarr-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/cleeryy/clarr:{{ .Version }}-arm64
      - ghcr.io/cleeryy/clarr:latest-arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/cleeryy/clarr:{{ .Version }}
    image_templates:
      - ghcr.io/cleeryy/clarr:{{ .Version }}-amd64
      - ghcr.io/cleeryy/clarr:{{ .Version }}-arm64
  - name_template: ghcr.io/cleeryy/clarr:latest
    image_templates:
      - ghcr.io/cleeryy/clarr:latest-amd64
      - ghcr.io/cleeryy/clarr:latest-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
